apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ramankms/weather-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: s3_bucket
        - name: AWS_REGION
          value: "us-east-1"
        livenessProbe:
          httpGet: { path: "/health", port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet: { path: "/health", port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 10